import { TeacherProfile } from "@/shared/types";

// JHI-v2-01 — Profil Guru card data (layout reference: /images/school/profil-guru.jpg)
export const teacherProfiles: TeacherProfile[] = [
  {
    id: "t-1",
    name: "Rahmat Dwi Djatmiko, S.Kom., M.M.",
    position: "Kepala Sekolah",
    image: "/images/school/assets/frontend/images/image1001.png",
    level: "PRINCIPAL",
    category: "STAFF",
    division: "Pimpinan",
  },
  {
    id: "t-2",
    name: "Endahing Nurweni R.A., S.E.",
    position: "Komite Sekolah",
    image: "",
    level: "PRINCIPAL",
    category: "STAFF",
    division: "Pimpinan",
  },
  {
    id: "t-3",
    name: "Dwi Setyawan, S.Kom.",
    position: "Wakil Kepala Bidang Kurikulum",
    image: "",
    level: "VP",
    category: "STAFF",
    division: "Kurikulum",
  },
  {
    id: "t-4",
    name: "Budi Santoso, S.T.",
    position: "Wakil Kepala Bidang Kesiswaan",
    image: "",
    level: "VP",
    category: "STAFF",
    division: "Kesiswaan",
  },
  {
    id: "t-5",
    name: "Rina Kartika, S.Kom., M.T.",
    position: "Guru Produktif RPL — Full Stack Developer",
    image: "",
    level: "TEACHER",
    category: "PRODUCTIVE",
    division: "Kurikulum",
  },
  {
    id: "t-6",
    name: "Andi Prasetyo, S.T.",
    position: "Guru Produktif TKJ — Network Engineer",
    image: "",
    level: "TEACHER",
    category: "PRODUCTIVE",
    division: "Kurikulum",
  },
  {
    id: "t-7",
    name: "Sari Dewi, S.Kom.",
    position: "Guru Produktif PG — Game Programmer",
    image: "",
    level: "TEACHER",
    category: "PRODUCTIVE",
    division: "Kurikulum",
  },
  {
    id: "t-8",
    name: "Agus Wijaya, S.Pd.",
    position: "Guru Matematika",
    image: "",
    level: "TEACHER",
    category: "NON_PRODUCTIVE",
    division: "Umum",
  },
  {
    id: "t-9",
    name: "Lina Marlina, S.Pd.",
    position: "Guru Bahasa Inggris",
    image: "",
    level: "TEACHER",
    category: "NON_PRODUCTIVE",
    division: "Umum",
  },
  {
    id: "t-10",
    name: "Joko Susilo, S.Pd.",
    position: "Guru Pendidikan Agama",
    image: "",
    level: "TEACHER",
    category: "NON_PRODUCTIVE",
    division: "Umum",
  },
  {
    id: "t-11",
    name: "Dewi Lestari, A.Md.",
    position: "Staff Administrasi",
    image: "",
    level: "TEACHER",
    category: "STAFF",
    division: "Tata Usaha",
  },
  {
    id: "t-12",
    name: "Fajar Nugroho, S.Kom.",
    position: "Teknisi Laboratorium Komputer",
    image: "",
    level: "TEACHER",
    category: "STAFF",
    division: "Sarana Prasarana",
  },
];

export const teacherCategoryLabels: Record<string, string> = {
  PRODUCTIVE: "Guru Produktif",
  NON_PRODUCTIVE: "Guru Non-Produktif",
  STAFF: "Staf & Tendik",
};
